# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/PIPELINE_3_SNAKE.INSTRUCTION.cache/wt [current_project]
set_property parent.project_path D:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/PIPELINE_3_SNAKE.INSTRUCTION.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/PIPELINE_3_SNAKE.INSTRUCTION.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files d:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/resources/I_pipemem37.coe
add_files d:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/resources/D_snakeDEMO.coe
read_verilog -library xil_defaultlib {
  D:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/resources/Counter_3_IO.v
  D:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/resources/ctrl_encode_def.v
  D:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/resources/EXT.v
  D:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/resources/Enter.v
  D:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/resources/GRE_array.v
  D:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/resources/HazardDectection.v
  D:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/resources/MIO_BUS.V
  D:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/resources/Multi_8CH32.v
  D:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/resources/NPC.v
  D:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/resources/PC.v
  D:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/resources/RF.v
  D:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/resources/SCPU.v
  D:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/resources/SPIO.v
  D:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/resources/SSeg7.v
  D:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/resources/alu.v
  D:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/resources/clk_div.v
  D:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/resources/ctrl.v
  D:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/resources/dm_controller.v
  D:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/resources/forward.v
  D:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/resources/TOP.v
}
read_ip -quiet d:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/PIPELINE_3_SNAKE.INSTRUCTION.srcs/sources_1/ip/ROM_D/ROM_D.xci
set_property used_in_implementation false [get_files -all d:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/PIPELINE_3_SNAKE.INSTRUCTION.srcs/sources_1/ip/ROM_D/ROM_D_ooc.xdc]

read_ip -quiet d:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/PIPELINE_3_SNAKE.INSTRUCTION.srcs/sources_1/ip/RAM_B/RAM_B.xci
set_property used_in_implementation false [get_files -all d:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/PIPELINE_3_SNAKE.INSTRUCTION.srcs/sources_1/ip/RAM_B/RAM_B_ooc.xdc]

read_edif D:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/resources/SPIO.edf
read_edif D:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/resources/SSeg7.edf
read_edif D:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/resources/Multi_8CH32.edf
read_edif D:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/resources/MIO_BUS.edf
read_edif D:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/resources/dm_controller.edf
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/constraints/icf-v-p.xdc
set_property used_in_implementation false [get_files D:/Vivadowork/PIPELINE_3_SNAKE.INSTRUCTION/constraints/icf-v-p.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
