# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Vivadowork/PIPELINE_4_APPLICATION/PIPELINE_4_APPLICATION.cache/wt [current_project]
set_property parent.project_path D:/Vivadowork/PIPELINE_4_APPLICATION/PIPELINE_4_APPLICATION.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Vivadowork/PIPELINE_4_APPLICATION/PIPELINE_4_APPLICATION.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/Vivadowork/PIPELINE_4_APPLICATION/resources/nn.coe
read_verilog -library xil_defaultlib {
  D:/Vivadowork/PIPELINE_4_APPLICATION/resources/CLK_DIV.v
  D:/Vivadowork/PIPELINE_4_APPLICATION/resources/ctrl_encode_def.v
  D:/Vivadowork/PIPELINE_4_APPLICATION/resources/EXT.v
  D:/Vivadowork/PIPELINE_4_APPLICATION/resources/GRE_array.v
  D:/Vivadowork/PIPELINE_4_APPLICATION/resources/HazardDectection.v
  D:/Vivadowork/PIPELINE_4_APPLICATION/resources/MIO_BUS.v
  D:/Vivadowork/PIPELINE_4_APPLICATION/resources/MULTI_CH32.v
  D:/Vivadowork/PIPELINE_4_APPLICATION/resources/NPC.v
  D:/Vivadowork/PIPELINE_4_APPLICATION/resources/PC.v
  D:/Vivadowork/PIPELINE_4_APPLICATION/resources/RF.v
  D:/Vivadowork/PIPELINE_4_APPLICATION/resources/SCPU.v
  D:/Vivadowork/PIPELINE_4_APPLICATION/resources/SEG7x16.v
  D:/Vivadowork/PIPELINE_4_APPLICATION/resources/alu.v
  D:/Vivadowork/PIPELINE_4_APPLICATION/resources/ctrl.v
  D:/Vivadowork/PIPELINE_4_APPLICATION/resources/dm.v
  D:/Vivadowork/PIPELINE_4_APPLICATION/resources/forward.v
  D:/Vivadowork/PIPELINE_4_APPLICATION/resources/xgriscv_fpga_top.v
}
read_ip -quiet D:/Vivadowork/PIPELINE_4_APPLICATION/PIPELINE_4_APPLICATION.srcs/sources_1/ip/imem/imem.xci
set_property used_in_implementation false [get_files -all d:/Vivadowork/PIPELINE_4_APPLICATION/PIPELINE_4_APPLICATION.srcs/sources_1/ip/imem/imem_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Vivadowork/PIPELINE_4_APPLICATION/constraints/icf-v-p.xdc
set_property used_in_implementation false [get_files D:/Vivadowork/PIPELINE_4_APPLICATION/constraints/icf-v-p.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top IP2SOC_Top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef IP2SOC_Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file IP2SOC_Top_utilization_synth.rpt -pb IP2SOC_Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
